apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: microservice-template-gateway
  namespace: app
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 30444
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: mydormroom-tls
      hosts:
        - microservice-template.mydormroom.com
        - microservice-template.mydormroom.dpdns.org
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: microservice-template-virtualservice
  namespace: app
spec:
  hosts:
    - microservice-template.mydormroom.com
    - microservice-template.mydormroom.dpdns.org
  gateways:
    - microservice-template-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ms-nextjs-template.app.svc.cluster.local
            port:
              number: 80
