apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-aggregator-cache
  labels:
    app: ms-aggregator-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-aggregator-cache
  template:
    metadata:
      labels:
        app: ms-aggregator-cache
    spec:
      containers:
      - name: ms-aggregator-cache
        image: yenyinglu/ms-aggregator-cache:6c45559e
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis.infra-net.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keyvault
              key: REDIS_PASSWORD
        - name: REDIS_CACHE_EXPIRATION_SECONDS
          value: "3600"
