apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-llm-orchestrator
  labels:
    app: ms-llm-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-llm-orchestrator
  template:
    metadata:
      labels:
        app: ms-llm-orchestrator
    spec:
      containers:
        - name: ms-llm-orchestrator
          image: yenyinglu/ms-llm-orchestrator:e0c14a6c
          ports:
            - containerPort: 8000
          env:
            - name: LANGFUSE_BASE_URL
              value: "http://langfuse-web.ai.svc.cluster.local:3000"
            - name: LITELLM_HOST
              value: "http://litellm.ai.svc.cluster.local:4000"
            - name: MCP_HOST
              value: "http://mcp-context-forge.ai.svc.cluster.local:4444/servers/1a6556c61e9a400ea537e7e73c05a2db/mcp"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: LITELLM_API_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: LANGFUSE_PUBLIC_KEY
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: LANGFUSE_SECRET_KEY
            - name: MCP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: MCP_TOKEN
