apiVersion: v1
kind: Service
metadata:
  name: ms-llm-orchestrator
spec:
  selector:
    app: ms-llm-orchestrator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
