apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-maple-drop-repo
  labels:
    app: ms-maple-drop-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-maple-drop-repo
  template:
    metadata:
      labels:
        app: ms-maple-drop-repo
    spec:
      containers:
        - name: ms-maple-drop-repo
          image: yenyinglu/ms-maple-drop-repo:9669811d
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mariadb.infra-net.svc.cluster.local:3306
            - name: MYSQL_USER
              value: mariadb
            - name: MYSQL_DATABASE
              value: TsmcMapleStoryV113Dev
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: MS-MAPLE-DROP-REPO-MYSQL_PASSWORD
            - name: KEYCLOAK_REALM_URL
              value: "https://keycloak.mydormroom.dpdns.org/realms/master"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
