apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-name-resolver
  labels:
    app: ms-name-resolver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-name-resolver
  template:
    metadata:
      labels:
        app: ms-name-resolver
    spec:
      containers:
        - name: ms-name-resolver
          image: yenyinglu/ms-name-resolver:76a95359
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-0.mongodb-headless.infra-net.svc.cluster.local:27017,mongodb-1.mongodb-headless.infra-net.svc.cluster.local:27017,mongodb-2.mongodb-headless.infra-net.svc.cluster.local:27017/?replicaSet=rs0" # Replace with your Kubernetes MongoDB service name
