apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-search-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-search-aggregator
  template:
    metadata:
      labels:
        app: ms-search-aggregator
    spec:
      containers:
      - name: ms-search-aggregator
        image: yenyinglu/ms-search-aggregator:2a780492
        ports:
        - containerPort: 8000
